### ISSUE TITLE
can you figure out what i did wrong?

### ISSUE THREAD

**Issue by MarioAlbe90** [pravdakotchestno/telegram-channel-backup#1]
**it says:**
Logged in successfuly as @r*****

Retrieving dialogs...
Traceback (most recent call last):
  File "C:\Users\+++\PycharmProjects\TGCannelCloner\tcb.py", line 67, in <module>
    exec(args.action + '()')
  File "<string>", line 1, in <module>
  File "C:\Users\+++\PycharmProjects\TGCannelCloner\tcb.py", line 38, in retrieve_channels
    username = '@' + dialog.entity.username
TypeError: can only concatenate str (not "NoneType") to str

**Comment by MarioAlbe90** [comment]
may this can help better:
o\PycharmProjects\TGCannelCloner>py tcb.py retrieve_channels --api_key 
++++:+++++++++++ --session sessionfile --from_channe
l -10013++++++06 --to_channel -10014++++++50
Connecting to the Telegram...
Logged in successfuly as @r+++
Retrieving dialogs...
Traceback (most recent call last):
  File "C:\Users\+++\PycharmProjects\TGCannelCloner\tcb.py", line 67, in <module>
    exec(args.action + '()')
  File "<string>", line 1, in <module>
  File "C:\Users\+++\PycharmProjects\TGCannelCloner\tcb.py", line 38, in retrieve_channels
    username = '@' + dialog.entity.username
TypeError: can only concatenate str (not "NoneType") to str
